blog/urls.py
from django.urls import path
from django.conf import settings 
from django.contrib import admin
from django.conf.urls.static import static 
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/delete/', views.post_remove, name="post_remove"),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('cv/new', views.CV_new, name='CV_new'),
    path('cv/edit', views.CV_edit, name='CV_edit'),
    path('cv/edit/skill/new',views.skills_new, name='skills_new'),
    path('cv/edit/skill/<int:pk>/edit',views.skill_edit, name='skill_edit'),
    path('cv/edit/skill/<int:pk>/delete/', views.skill_remove, name="skill_remove"),
    path('cv/edit/work/new', views.work_new, name='work_new'),
    path('cv/edit/work/<int:pk>/edit', views.work_edit, name='work_edit'),
    path('cv/edit/work/<int:pk>/delete', views.work_remove, name='work_remove'),
    path('cv/edit/qual/new', views.qual_new, name='qual_new'),
    path('cv/edit/qual/<int:pk>/edit', views.qual_edit, name='qual_edit'),
    path('cv/edit/qual/<int:pk>/delete', views.qual_remove, name='qual_remove'),

]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', views.LoginView.as_view(),name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'),name='logout'),
    path('', include('blog.urls'))
]

blog/models.py
from django.conf import settings
from django.db import models
from django import forms
from django.utils import timezone
import os

class Skill(models.Model):
    skill = models.CharField(max_length=200)
    description = models.TextField()
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Qual(models.Model):
    qualification = models.CharField(max_length=200)
    subject = models.CharField(max_length=200)
    grade = models.CharField(max_length=200)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()

    coverImage = models.ImageField(upload_to='images/',default="/images/default.jpg")
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class CV(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    summary = models.TextField()
    interests = models.TextField()
    references = models.TextField()

    def publish(self):
        self.save()

    def __str__(self):
        return self.title




class Work(models.Model):
    title = models.TextField(max_length=200)
    company = models.TextField()
    dateStarted = models.DateField(blank=True, null=True)
    dateEnd = models.DateField(blank=True, null=True)
    published_date = models.DateTimeField(blank=True, null=True)
    

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

blog/forms.py
from django import forms

from .models import *

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title','coverImage', 'text')
        widgets = {
        	'title' : forms.TextInput(attrs={'placeholder': 'Enter Post title'}),
        	'text' : forms.Textarea(attrs={'placeholder' : 'Type your blog here...', 'oninput' : 'this.style.height = "";this.style.height = this.scrollHeight + "px"','class':  'textarea'})
        	
        }



class CVForm(forms.ModelForm):

    class Meta:
        model = CV
        fields = ('summary','interests','references')
        widgets = {
        	'summary' : forms.Textarea(attrs={'placeholder': 'Enter Summary here','oninput' : 'this.style.height = "";this.style.height = this.scrollHeight + "px"','class':  'textarea'}),
        	'interests' : forms.Textarea(attrs={'placeholder': 'Type here','oninput' : 'this.style.height = "";this.style.height = this.scrollHeight + "px"','class':  'textarea'}),
        	'references' : forms.Textarea(attrs={'placeholder': 'Type here','oninput' : 'this.style.height = "";this.style.height = this.scrollHeight + "px"','class':  'textarea'})
        }






class SkillForm(forms.ModelForm):
    class Meta:
        model = Skill
        fields = {'skill','description'}
        widgets = {
            'skill' : forms.TextInput(attrs={'placeholder': 'Skill Name','oninput' : 'this.style.height = "";this.style.height = this.scrollHeight + "px"',}),
            'description' : forms.TextInput(attrs={'placeholder': 'Skill description' , 'oninput' :'this.style.height = "";this.style.height = this.scrollHeight + "px"','class':  'textarea'})
  
        }



class QualForm(forms.ModelForm):
    class Meta:
        model = Qual
        fields = {'qualification','subject','grade'}
        widgets = {
            'qualification' : forms.TextInput(attrs={'placeholder': 'Qualification','oninput' : 'this.style.height = "";this.style.height = this.scrollHeight + "px"',}),
            'subject' : forms.TextInput(attrs={'placeholder': 'Area of Study' , 'oninput' :'this.style.height = "";this.style.height = this.scrollHeight + "px"'}),
            'grade' : forms.TextInput(attrs={'placeholder': 'Grade Achieved' , 'oninput' :'this.style.height = "";this.style.height = this.scrollHeight + "px"'})

  
        }




class WorkForm(forms.ModelForm):
    dateStarted = forms.DateField(input_formats=['%d/%m/%Y'])
    dateEnd = forms.DateField(input_formats=['%d/%m/%Y'])
    class Meta:
        model = Work
        fields = {'title','company','dateStarted','dateEnd'}
        widgets = {
            'title' : forms.TextInput(attrs={'placeholder': 'Job title','oninput' : 'this.style.height = "";this.style.height = this.scrollHeight + "px"','class':  'textarea'}),
            'company' : forms.TextInput(attrs={'placeholder': 'Company Name' , 'oninput' :'this.style.height = "";this.style.height = this.scrollHeight + "px"','class':  'textarea'}),
            'dateStarted' : forms.DateInput(attrs={'class': 'form-control datetimepicker-input', 'data-target': '#datetimepicker1'}),
            'dateEnd' : forms.DateInput(attrs={'class': 'form-control datetimepicker-input', 'data-target': '#datetimepicker2'})
  
        }

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post,CV,Skill,Work,Qual
from django.utils import timezone
from .forms import PostForm, CVForm, SkillForm,WorkForm,QualForm
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required

# Create your views here.

def post_list(request):
	posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	skills  = Skill.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	workExp = Work.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	qualEd = Qual.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	my_CV = CV.objects.first()
	return render(request, 'blog/post_list.html', {'posts': posts, 'CV':my_CV, 'skills':skills,'workExp': workExp,'qualifications':qualEd})

@login_required
def post_remove(request,pk):
	post = get_object_or_404(Post, pk=pk)
	if request.method == "POST":
		post.delete()
		return redirect('post_list')
	else:
		return redirect('post_list')

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST,request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_list')
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST,request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form, 'post': post})

@login_required
def CV_new(request):
    if request.method == "POST":
        form = CVForm(request.POST,request.FILES)
        if form.is_valid():
            cv = form.save(commit=False)
            cv.author = request.user
            cv.published_date = timezone.now()
            cv.save()
            return redirect('post_list')
    else:
        form = CVForm()
    return render(request, 'blog/cv_edit.html', {'form': form})

@login_required
def CV_edit(request):
    cv = CV.objects.first()
    skills  = Skill.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    workExp = Work.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    qualEd = Qual.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    if request.method == "POST":
        form = CVForm(request.POST,request.FILES,instance=cv)
        if form.is_valid():
            cv = form.save(commit=False)
            cv.author = request.user
            cv.published_date = timezone.now()
            cv.save()
            return redirect('post_list')
    else:
        form = CVForm(instance=cv)
    return render(request, 'blog/cv_edit.html', {'form': form, 'skills':skills , 'workExp':workExp, 'qualifications':qualEd })

@login_required
def skills_new(request):
    cv= CV.objects.first()
    form = CVForm(request.POST,request.FILES,instance=cv)
    skills  = Skill.objects.filter(published_date__lte=timezone.now()).order_by('published_date')

    if request.method == "POST":
        skill_form = SkillForm(request.POST,request.FILES)
        if skill_form.is_valid():
            skill_form = skill_form.save(commit=False)
            skill_form.author = request.user
            skill_form.published_date = timezone.now()
            skill_form.save()
            return redirect('CV_edit')
    else:
        skill_form = SkillForm()
    return render(request, 'blog/skill_edit.html', {'form': form, 'skill_form': skill_form, "skills": skills,})

@login_required
def skill_edit(request,pk):
    skill = get_object_or_404(Skill, pk=pk)
    if request.method == "POST":
        form = SkillForm(request.POST,request.FILES,instance=skill)
        if form.is_valid():
            skill = form.save(commit=False)
            skill.author = request.user
            skill.published_date = timezone.now()
            skill.save()
            return redirect('CV_edit')
    else:
        form = SkillForm(instance=skill)
    return render(request, 'blog/skill_edit.html', {'skill_form': form})

@login_required
def skill_remove(request,pk):
	skill = get_object_or_404(Skill, pk=pk)
	if request.method == "POST":
		skill.delete()
		return redirect('CV_edit')
	else:
		return redirect('CV_edit')

@login_required
def work_new(request):
    cv= CV.objects.first()
    form = CVForm(request.POST,request.FILES,instance=cv)
    if request.method == "POST":
        work_form = WorkForm(request.POST,request.FILES)
        if work_form.is_valid():
            work_form = work_form.save(commit=False)
            work_form.author = request.user
            work_form.published_date = timezone.now()
            work_form.save()
            return redirect('CV_edit')
    else:
        work_form = WorkForm()
    return render(request, 'blog/work_edit.html', {'form': form, 'work_form': work_form})

@login_required
def work_edit(request,pk):
    work = get_object_or_404(Work, pk=pk)
    if request.method == "POST":
        form = WorkForm(request.POST,request.FILES,instance=work)
        if form.is_valid():
            work = form.save(commit=False)
            work.author = request.user
            work.published_date = timezone.now()
            work.save()
            return redirect('CV_edit')
    else:
        form = WorkForm(instance=work)
    return render(request, 'blog/work_edit.html', {'work_form': form})

@login_required
def work_remove(request,pk):
	work = get_object_or_404(Work, pk=pk)
	if request.method == "POST":
		work.delete()
		return redirect('CV_edit')
	else:
		return redirect('CV_edit')

@login_required
def qual_new(request):
    cv= CV.objects.first()
    form = CVForm(request.POST,request.FILES,instance=cv)
    if request.method == "POST":
        qual_form = QualForm(request.POST,request.FILES)
        if qual_form.is_valid():
            qual_form = qual_form.save(commit=False)
            qual_form.author = request.user
            qual_form.published_date = timezone.now()
            qual_form.save()
            return redirect('CV_edit')
    else:
        qual_form = QualForm()
    return render(request, 'blog/qual_edit.html', {'form': form, 'qual_form': qual_form})

@login_required
def qual_edit(request,pk):
    qual = get_object_or_404(Qual, pk=pk)
    if request.method == "POST":
        form = QualForm(request.POST,request.FILES,instance=qual)
        if form.is_valid():
            qual = form.save(commit=False)
            qual.author = request.user
            qual.published_date = timezone.now()
            qual.save()
            return redirect('CV_edit')
    else:
        form = QualForm(instance=qual)
    return render(request, 'blog/qual_edit.html', {'qual_form': form})

@login_required
def qual_remove(request,pk):
	qual = get_object_or_404(Qual, pk=pk)
	if request.method == "POST":
		qual.delete()
		return redirect('CV_edit')
	else:
		return redirect('CV_edit')

blog/templates/blog/base.html
{% load static %}
<html>
    <head>
        <title>Django Girls blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link rel="stylesheet" href="{% static 'css/cv.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>
        <script type="text/javascript" src="{% static 'js/helper.js' %}" ></script>
        <img src="./media/images/default.jpg" style="display: none">
    </head>
    <body>
        <div class="page-header" >
                  {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" class="top-menu">{{ user.username }} <span class="glyphicon glyphicon-user"></span></a>
            {% else %}
                <a href="{% url 'login' %}" class="top-menu"> <span class="glyphicon glyphicon-lock"></span></a>
            {% endif %}
            <h1 style="text-align: center; font-weight: bold; "> <a href="/" > Isaac Horry</a></h1>
            
      

            <span id="titlebreak"></span>
        </div>
        <div class=content>
            <div class=content-align>
                {% block content %}
                {% endblock %}
            </div>
                
        </div>
    </body>
</html>

blog/templates/blog/cv_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post-detail"  >
	    <form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
	         
        <div >
            <div class="summary-div">
            {{ form.summary}}
            </div>
            <div class="horizontal-flex">
                <div class = "skills-div">
           
               
                {% for skill in skills %}
                    <div class="skill-container">
                        <ul>
                            {% if user.is_authenticated %}
                                <a class="btn btn-default" id = "edit_post" href="{% url 'skill_edit' pk=skill.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
                                <form action= "{% url 'skill_remove' pk=skill.pk %}" method="POST">{% csrf_token %}
                                    <button id = "delete_post"  class="btn btn-default" type="submit" type=><span class="glyphicon glyphicon-trash"></span></button>
                                </form>
                            {% endif %}
                            <li>{{ skill.skill }}<br /><span>{{ skill.description }}</span></li>
                        </ul>

                    </div>

                {% endfor %}
                <div class="addform">
                      {% if user.is_authenticated %}
                        <a href="{% url 'skills_new' %}" id="id_skills" ><span id= "plusicon-colourchange"class="glyphicon glyphicon-plus" id="id_skills"></span></a>
                    {% endif %}
                </div>

                </div>


                <div class="inner-vert-flex">

                    <div class="qualifications-div ">
                
                        {% for qual in qualifications %}
                            <div class="qual-container">
                                <ul>
                                    {% if user.is_authenticated %}
                                        <a class="btn btn-default" id = "edit_post" href="{% url 'qual_edit' pk=qual.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
                                        <form action= "{% url 'qual_remove' pk=qual.pk %}" method="POST">{% csrf_token %}
                                            <button id = "delete_post"  class="btn btn-default" type="submit" type=><span class="glyphicon glyphicon-trash"></span></button>
                                        </form>
                                    {% endif %}
                                    <li>{{ qual.qualification }}<br /><span>{{ qual.subject }}
                                        <br /> <span>{{ qual.grade }}</span></span></li>
                                </ul>

                            </div>

                        {% endfor %}
                        <div class="addform">
                               {% if user.is_authenticated %}
                                <a href="{% url 'qual_new' %}" id="id_qual"><span id= "plusicon-colourchange"class="glyphicon glyphicon-plus"></span></a>
                            {% endif %}
                        </div>


                    </div>

                        <div class="workExp-div">
                      
                      
                        {% for work in workExp %}
                            <div class="workExp-container">
                                <ul>
                                    {% if user.is_authenticated %}
                                        <a class="btn btn-default" id = "edit_post" href="{% url 'work_edit' pk=work.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
                                        <form action= "{% url 'work_remove' pk=work.pk %}" method="POST">{% csrf_token %}
                                            <button id = "delete_post"  class="btn btn-default" type="submit" type=><span class="glyphicon glyphicon-trash"></span></button>
                                        </form>
                                    {% endif %}

                                    <li>{{ work.dateStarted }} - {{ work.dateEnd }}<br /><span>{{ work.title }}
                                        <br /> <span>{{ work.company }}</span></span></li>
                                </ul>

                            </div>


                        {% endfor %}
                          <div class="addform">
                              {% if user.is_authenticated %}
                            <a href="{% url 'work_new' %}" id="id_workExp"><span id= "plusicon-colourchange"class="glyphicon glyphicon-plus"></span></a>
                             {% endif %}
                        </div>



                        </div>
                </div>
            </div>


            <div class="interests-div">
                {{ form.interests}}
            </div>

            <div class="references-div">
                {{ form.references}}
            </div>

        <div>
            <button type="submit" class="save btn btn-default" id="id_submit">Save</button>

        </div>
            
        </div>


	</div>






   
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class= "settings-detail"> 
            {% if user.is_authenticated %}
                
                 <form action= "{% url 'post_remove' pk=post.pk %}" method="POST">{% csrf_token %}
                    <a class="btn btn-default" id = "edit_post" href="{% url 'post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
                    <button id = "delete_post" onclick="confirm('Are you want to delete this post?')" class="btn btn-default" type="submit" type=><span class="glyphicon glyphicon-trash"></span></button>
                </form>
            {% endif %}
    </div>
    <div  class="post-detail">
        
 
        {% if post.published_date %}
            <div class="date">
               {{ post.author }}, {{ post.published_date }}
            </div>
        {% endif %}
        
        <h2>{{ post.title }}</h2>
        <div class="image-container">
            <img src= "{{ post.coverImage.url }}">
        </div>
        
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <div  class="post-detail">
	    <form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
	        {{ form.title }} 
	    	
	    	<div class=fileinput-container>
	    			<img id = "coverImage" src="{{ post.coverImage.url }}" alt='' class=''> 
	    			<div id="hidden_items">
	    				{{ form.coverImage }}
	    			</div>
	    			
	    			<label for='id_coverImage' class="image-upload">Choose file</label>

	    	</div>  	
	    	 
	    	{{ form.text }}

	    	

	        
	        <button type="submit" class="save btn btn-default">Save</button>
	    </form>
	</div>
   
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block content %}

    <div class="CV_container" style="align-content: center;">
       {% if CV %}
            <div id="summary-div1">
                <p>{{ CV.summary }}</p>
            </div>
            
       {% else %}
            {% if user.is_authenticated %}
                <a href="{% url 'CV_new' %}" id="CV_placeholder"> Add New CV </a>
            {% else %}
                No CV to show :(
            {% endif %}
       {% endif %}

       <button id = "CV_viewfull"  >View full CV</button>


       <div id="CV_full" class="fade-out"> 


            <div > 
                {% if user.is_authenticated %}
                    
                    
                     <form action= "" method="POST">{% csrf_token %}
                        <a class="btn btn-default" href="{% url 'CV_edit' %}" id = "edit_post" ><span class="glyphicon glyphicon-pencil"></span></a>
                        <button id = "delete_post" onclick="confirm('Are you want your CV?')" class="btn btn-default" type="submit" type=><span class="glyphicon glyphicon-trash"></span></button>
                    </form>
                {% endif %}
            </div>

            <div  class="cv-detail">
                
                <div class="summary-div">
                    <h4>Summary</h4>
                    <p>{{ CV.summary }}</p>
                </div>
                <div class="horizontal-flex">
                     <div class="skills-div">
                        <h4>Skills and Experience</h4>
                        {% for skill in skills %}
                        <div class="skill-container">
                            <ul>
                                <li><b>{{ skill.skill }}</b><br /><span>{{ skill.description }}</span></li>
                            </ul>

                        </div>

                        {% endfor %}

                    </div>

                    <div class="inner-vert-flex">
                        <div class="qualifications-div">
                            <h4>Qualifications and Education</h4>
                            {% for qual in qualifications %}
                                <div class="qual-container">
                                    <ul>
                                        <li>{{ qual.qualification }}<br /><span>{{ qual.subject }}
                                            <br /> <span>{{ qual.grade }}</span></span></li>
                                    </ul>

                                </div>

                            {% endfor %}

                        </div>


                        <div class="workExp-div">
                            <h4>Previous Work Experience</h4>
                            {% for work in workExp %}
                                <div class="workExp-container">
                                    <ul>

                                        <li >{{ work.dateStarted }} - {{ work.dateEnd }}<br /><span>{{ work.title }}
                                            <br /> <span>{{ work.company }}</span></span></li>
                                    </ul>

                                </div>

                            {% endfor %}
                        </div>
                    </div>

                </div>
                   
                <div class="interests-div">
                    <h4>Other Interests</h4>
                    <p class="list1">{{CV.interests}}l</p>
                </div>

                <div class="references-div">
                    <h4>References</h4>
                     <p class="list1">{{CV.references }} </p>
                </div>
                
               
         
            </div>
        </div>
    </div>
       
  
    <div id="blog_div" class="slide-in">
             <div class="blog-header">
            {% if user.is_authenticated %}
                    <a href="{% url 'post_new' %}" class="top-menu"><span id= "plusicon-colourchange"class="glyphicon glyphicon-plus"></span></a>
            {% endif %}
            <h1 style="text-align: center;"> <a  > My Blog</a></h1>
            <span id="titlebreak"></span>
    </div>
    <div class="flex-container"> 
        {% for post in posts %}
        <div  class="post">
            <h2 class="title-header">{{ post.title }}</h2>
            <div class="image-container">
                <img style="height:300px" src= "{{ post.coverImage.url }}">
            </div>

            <p class="post_list-gradient">{{ post.text|truncatewords:60 }}</p>
            {% if post.text|length > 60 %}
                <a style="float:right; padding-right: 2px;" href="{% url 'post_detail' pk=post.pk %}">Read More</a>
            {% endif %}
        </div>
    {% endfor %}
    </div>

    </div>


{% endblock %}

blog/templates/blog/qual_edit.html
{% extends 'blog/base.html' %}

{% block content %}
            <div>

                <form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}

                	{{ qual_form.qualification }}
                	{{ qual_form.subject }}
                	{{ qual_form.grade }}

                <button type="submit" class="save btn btn-default">Save</button>

	             
	       </div>
   
{% endblock %}

blog/templates/blog/skill_edit.html
{% extends 'blog/base.html' %}

{% block content %}
            <div>

                <form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}


                    {{ skill_form.skill }}
                    {{ skill_form.description }}

                <button type="submit" class="save btn btn-default">Save</button>

	             
	       </div>
   
{% endblock %}